doing profile company
annguyenquang/Job-Finder-Client pull request #1
Opened 2024-10-14 14:45 UTC by annguyenquang

2024-10-18 04:48 UTC, annguyenquang reviewed
review

2024-10-18 04:48 UTC, annguyenquang commented on core/models/CompanyModel/CompanyDetail.ts
> +    accountId: number;
string

2024-10-18 04:48 UTC, annguyenquang commented on core/models/JobModel/Job.ts
> +    position: string,
location

2024-10-18 04:48 UTC, annguyenquang commented on core/models/JobModel/Job.ts
> +}
Update theo card: https://trello.com/c/R6U9qAtg

2024-10-18 04:48 UTC, annguyenquang commented on core/services/JobService/JobService.tsx
> +        console.log(error);
console log

2024-10-18 04:48 UTC, annguyenquang commented on components/company-profile/Breadcrumb.tsx
> +    console.info('You clicked a breadcrumb.');
remove console

2024-10-18 04:49 UTC, nqanpreciofishbone commented on core/models/JobModel/Job.ts
> +    position: string,
abc

2024-10-18 06:53 UTC, nqanpreciofishbone requested changes

2024-10-18 06:53 UTC, nqanpreciofishbone commented on components/company-profile/Banner.tsx
> +                image="https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/v4/image/normal-company/cover/company_cover_1.jpg"
đừng dùng magic string

2024-10-18 06:53 UTC, nqanpreciofishbone commented on core/models/JobModel/JobStatus.ts
> +    Close = 'Close',
Closed

2024-10-18 06:53 UTC, nqanpreciofishbone commented on components/company-profile/Share.tsx
> +import { Alert, Box, Card, CardContent, IconButton, Snackbar, TextField } from '@mui/material';
import kiểu: import Alert from '@mui/material/Alert'
cho từng component

2024-11-07 03:19 UTC, annguyenquang commented on components/company-profile/Recruitment.tsx
> +];
Dùng location service

2024-11-07 14:25 UTC, annguyenquang commented on components/company-profile/Recruitment.tsx
>                              onChange={handleSearchChange} // Thêm sự kiện thay đổi cho ô tìm kiếm
xóa cmt

2024-11-07 14:28 UTC, annguyenquang commented on components/company-profile/Recruitment.tsx
> +import { useLocationStore } from '@/stores/LocationStore';
chuyển thành @/store

2024-11-07 14:29 UTC, annguyenquang commented on components/company-profile/Recruitment.tsx
> +    }, locationStore.allProvince);
useEffect kh dùng thì xóa đi

2024-11-07 14:51 UTC, annguyenquang commented on components/company-profile/Recruitment.tsx
> +    const jobsPerPage = 4; // Số công việc trên mỗi trang
check kĩ xem còn chỗ nào có cmt không xóa luôn

2024-11-07 14:53 UTC, merged