Bao/company application UI
annguyenquang/Job-Finder-Client pull request #30
Opened 2024-12-26 11:07 UTC by 271baotg

Task link: https://trello.com/c/gCKlhphC

2024-12-26 13:44 UTC, annguyenquang commented on core/models/enum/ApplicationStatus.ts
> +export enum StatusCodes {
tên hơi tối nghĩa, đổi tên thành JobApplicationStatus

2024-12-26 13:46 UTC, annguyenquang commented on core/stores/JobStore/JobDetailStore.ts
> +      console.log('Application res: ', res)
xóa console.log

2024-12-26 13:47 UTC, annguyenquang commented on core/stores/JobStore/JobDetailStore.ts
> +      await new Promise((resolve) => setTimeout(resolve, 2000))
??

2024-12-26 13:49 UTC, annguyenquang commented on components/job-detail/ApllicationTable.tsx
> +  console.log('List Users: ', props.users)
xóa console.log

2024-12-26 13:50 UTC, annguyenquang commented on components/job-detail/ApllicationTable.tsx
> +  return { name, calories, fat, carbs, protein }
what for ?

2024-12-26 13:51 UTC, annguyenquang commented on components/job-detail/ApplicationPanel.tsx
> +    console.log('Job applications: ', jobDetailStore.jobApplication)
console.log

2024-12-26 13:52 UTC, annguyenquang commented on core/stores/JobStore/JobDetailStore.ts
> +import { Console } from 'console'
what for

2024-12-26 13:54 UTC, annguyenquang requested changes
fix this

2024-12-27 04:46 UTC, 271baotg commented on core/stores/JobStore/JobDetailStore.ts
> +      await new Promise((resolve) => setTimeout(resolve, 2000))
Để giả lập delay

2024-12-27 09:06 UTC, annguyenquang reviewed
lgtm

2024-12-27 09:07 UTC, merged