Chanh/job detail page
annguyenquang/Job-Finder-Client pull request #5
Opened 2024-11-04 03:21 UTC by Zues382003

Task Link 1: https://trello.com/c/XoSDgcSF
Task Link 2: https://trello.com/c/T30cxB0v

2024-11-04 03:27 UTC, annguyenquang commented on app/globals.css
file này có còn dùng không ?

2024-11-04 03:28 UTC, annguyenquang commented on components/job-detail/Breadcrumb.tsx
> +}
vì sao cần prevenDefault ở đây?

2024-11-04 03:30 UTC, annguyenquang commented on components/job-detail/CompanyIntro.tsx
> +                    </img>
Thử dùng Image của next/Image để tối ưu hơn

2024-11-04 03:31 UTC, annguyenquang commented on components/job-detail/JobInfo.tsx
> +                        </img>
Sử dụng Image của nextjs

2024-11-04 03:32 UTC, annguyenquang commented on components/job-detail/JobList.tsx
> +            location: "Quận Phú Nhuận, Thành phố Hồ Chí Minh",
xóa fake data

2024-11-04 03:32 UTC, annguyenquang commented on components/job-detail/JobList.tsx
> +            location: "Quận Phú Nhuận, Thành phố Hồ Chí Minh",
fake data cho công việc tương tự phải không

2024-11-04 03:34 UTC, annguyenquang requested changes

2024-11-04 03:34 UTC, annguyenquang commented on core/services/JobService/JobService.tsx
chỉ file component mới đặt là .tsx

2024-11-04 03:34 UTC, annguyenquang commented on tailwind.config.ts
> +        colorPimaryText: 'var(--PRIMARYTEXT)'
cái này có còn sử dụng không

2024-11-04 12:20 UTC, Zues382003 commented on app/globals.css
còn nha

2024-11-04 12:22 UTC, Zues382003 commented on components/job-detail/Breadcrumb.tsx
> +}
Để vậy thôi, mốt khi truyền danh sách job có thể xóa

2024-11-04 12:24 UTC, Zues382003 commented on components/job-detail/CompanyIntro.tsx
> +                    </img>
đã fix

2024-11-04 12:25 UTC, Zues382003 commented on components/job-detail/JobInfo.tsx
> +                        </img>
đã fix

2024-11-04 12:26 UTC, Zues382003 commented on components/job-detail/JobList.tsx
> +            location: "Quận Phú Nhuận, Thành phố Hồ Chí Minh",
Đúng rồi.

2024-11-04 12:26 UTC, Zues382003 commented on core/services/JobService/JobService.tsx
đã fix

2024-11-04 12:27 UTC, Zues382003 commented on tailwind.config.ts
> +        colorPimaryText: 'var(--PRIMARYTEXT)'
còn sử dụng bên company và có thể tái sử dụng lại bên job

2024-11-06 01:41 UTC, annguyenquang commented on components/job-detail/Breadcrumb.tsx
> +}
kh dùng nữa thì xóa đi nha ô

2024-11-07 02:35 UTC, merged